# Generated by Django 3.1.7 on 2021-03-16 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(max_length=400),
        ),
    ]
